# Backup.py sample sources file
# To backup new entries, add a mapping
# of the time '<LABEL>=<PATH>'
#

# directories end with a slash...
photos=/home/marco/Pictures/
templates=/home/marco/Documents/LatexTemplate
issue=/etc/issue
