name: backup.py
on: [push,pull_request,workflow_dispatch]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y python3 tar gpg

      - name: Run unit tests
        run: |
          python3 test_backup.py backup.py
